# Here is distiller example config
#
# list of available FUSE operations:
# access, chmod, chown, fsync, getattr, getxattr, link, listxattr, mkdir,
# mknod, open, read, readdir, readlink, release, removexattr, rename, rmdir,
# setxattr, statfs, symlink, truncate, unlink, utime, utimens, write.

[filter]
    # By default, logged all success operations
    open="success"
    write="success"
    read="all"
    getattr="never"
    unlink="unsuccess"

[exclude]
    # Paths (prefixes) excluded from logging
    paths=["/include/exclude"]

[include_only]
    # Paths (prefixes) included into logging
    # If empty, all subdirs are included
    # paths=["/include"]
